name: Build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_unit:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependenceis
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Add name
      run: echo "Vasil556"

  build_test_ui:
    needs: build_test_unit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependenceis
      run: npm install
    - name: install playwright
      run: npx playwright install
    - name: Start app
      run: npm start &  
    - name: Run ui tests
      run: npm run test:ui
    - name: Add name
      run: echo "Vasil556"